language: groovy
jdk:
- oraclejdk8
branches:
  only:
  - master
before_install:
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh
- ala_travis_grails_setup_env

script: 
- ala_travis_grails_build
env:
  global:
  - secure: "wTJYsmwt9W+p8VNOuA9VT4mg567PtSrFAVhD+3rJSPRe7fFS+GKU8oALvZgBIT6TeBzoTwNxmdujWUwpheO+Xz/KB6Kp6s3j8w7IK4XM5lxkISJ54mFq2kQ6b9d2twida+mCcKxQ0Rls+Ob8XS6AJco80j5wl6ZYh2BUVW4NEaIrIOEfjUfo6jGgwA+UqVIG1MkvgNQ5/iqKhu6O9+NjbqkKqjM5HmoSLTHUyhuX1xX/MRAOGP8wnJ0DWvIv2MxaqKsWiK0HHqOF1k5AxXEC5qvL4T5uPmBP/YxWZsHuKhM9aCan8ZzbB3mU7zbwkM+1F57koYY67DQRbKgptKIWLMWKIk3AL+WbA59o9cfgjKRNB54oYzJvmqTl+uKeJfY1KmunlHivenaiyrOYVvUvOZr0I0J5UMxTpWd/hxbd1eRMtsN6u58L05hEFt/L7Yt3Fn3caXW/rJVl4KI31T6imcxwICnJ50d4bwfkDHmWQTHLxH9VyLq+U9inRWNVdVsweYXld8MekEhGFx4gbwm537Lz5Dkm3lhTxDcW9A91+oIUUza7D1GSG/kawSl7d/v7UQQPUHChdkZQYy6mB6UAAcfBXl/a24P5N3VwrAJiyjO5MKGwZjjZWNvVecN/cg7/l0fcHAy4AIYnCsPvNWEgtyQoGxXQSrU6L1rW9423r54="
  - secure: "LaPc6sSXRKDzny1nycy4RjHXw3eX51l6lEjV5z62n7VbH+5xpI6xt6WABOIC1oSkoHdVA8A1c8avGg2o6JAKqhQHuL/Nb86etp0+3AwR7MbLNr80hHpVw1ZqQO2qNNgp3qCi3snVovoseFS+9Ep3eRJE84Mev+sMcygtLpA8B/adiaBkL/Segs/jKXsNo/LCThOBcdhGF8zXSAVvhsX/ef206EdUx20qZRjsTXAoHBOT1OI89T9+/bGokJAjx6HYk7V4D7As2DSNZJPsIAkDYucWrTY7treLxRieDvlYT6HES2O34UlB3f8Mc1sBsLOWt3U5U6gFHfRSlVTSnhG2X2KkpsFYcDBDaQU4QrJbrPz9tYOnNEcQAvtzK4PUdflUiCex+tuhCsa3eLhtlJPUgrGqMyWV0qweIcXDZYVCY2XMGFzFEpm81ET82xnz4efzbK8Yj58GbNP7KSeztLqhrhv1kO/MT99nUVvB8FA9eGlxBioA33ERdY3w5vOZ/p5f9gKlAzWF1LiqLgYcDdvU8Ro6lohPtAsU0kETvUmpN0nP2xfiWaUtRzDRbBF5UWMnXCZuJAXAloVtEK0zqX5g62yJ1iyKv5kf8GXPxzOKJzCkjBPzO+BZ60sK4CDDAMXjYS0ifidgIFKBeWOEFz+sZDVAGu/NttcNvNfUZbCGFYE="
