language: groovy
jdk:
- oraclejdk7
branches:
  except:
  - trunk
before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- GRAILS_VERSION=`grep '^app\.grails\.version=' ./application.properties | sed -e
  's/^app\.grails\.version=//g'`
- gvm install grails $GRAILS_VERSION || true
before_script:
- mkdir -p ~/.grails; wget -q -O ~/.grails/settings.groovy https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_grails_settings_new.groovy

script: 
  - MAVEN_REPO="ala-repo-snapshot"; grep 'def version =' ./FieldcaptureTestGrailsPlugin.groovy | grep -q "\-SNAPSHOT"; if [ "$?" = "1" ]; then MAVEN_REPO="ala-repo-release"; fi;
  - grails clean; grails refresh-dependencies --non-interactive; grails compile --non-interactive
  - '[ "$TRAVIS_PULL_REQUEST" != "false" ] || grails prod maven-deploy --repository=$MAVEN_REPO --non-interactive'
env:
  global:
  - secure: <TBA>
  - secure: <TBA>
